import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Image from "next/image"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <div className={styles.header}>
          <h1>Take a look at these pages </h1>
        </div>
       
        <div className={styles.links}>
        <div className={styles.useEffectOne}>
        <h1> #1</h1>
        <Link href="/useEffectOne">useEffectOne</Link>
        </div> 
        <div className={styles.useEffectTwo}>
        <h1>#2</h1>
        <Link href="/useEffectTwo">useEffectTwo</Link>
        </div>
        <div className={styles.useEffectThree}>
        <h1>#3</h1>
        <Link href="/useEffectThree">useEffectThree</Link>
        </div>
        <div className={styles.carousel}>
        <h1>#4</h1>
        <Link href="/carouselPage">Carousel Page</Link>
        </div>
        </div>      
      </main>
    </>
  )
}
